<?php
session_start();
require_once('../../db_connect.php');
require_once('../../includes/auth.php');
require_once('../helpers/standings_helper.php');

// Check authorization
if (!isset($_SESSION['user_id']) || $_SESSION['role'] !== 'admin') {
    http_response_code(403);
    echo json_encode(['error' => 'Access denied']);
    exit;
}

$leagueId = (int) ($_GET['league'] ?? $_SESSION['league_id'] ?? 0);
$format = $_GET['format'] ?? 'full';

if (!$leagueId) {
    http_response_code(400);
    echo json_encode(['error' => 'Invalid league ID']);
    exit;
}

// Get league info
$leagueQuery = $conn->prepare("SELECT name, abbreviation FROM leagues WHERE league_id = ?");
$leagueQuery->bind_param("i", $leagueId);
$leagueQuery->execute();
$league = $leagueQuery->get_result()->fetch_assoc();

if (!$league) {
    http_response_code(404);
    echo json_encode(['error' => 'League not found']);
    exit;
}

$standings = getLeagueStandings($conn, $leagueId);
$stats = getStandingsStats($conn, $leagueId);

switch ($format) {
    case 'full':
        $text = generateFullStandingsText($league, $standings, $stats);
        break;
    case 'top5':
        $text = generateTop5StandingsText($league, $standings);
        break;
    case 'results':
        $results = getRecentResults($conn, $leagueId, 5);
        $text = generateResultsText($league, $results);
        break;
    case 'fixtures':
        $fixtures = getUpcomingFixtures($conn, $leagueId, 5);
        $text = generateFixturesText($league, $fixtures);
        break;
    case 'weekly':
        $text = generateWeeklyReportText($league, $standings, $stats, $conn, $leagueId);
        break;
    default:
        http_response_code(400);
        echo json_encode(['error' => 'Invalid format']);
        exit;
}

header('Content-Type: application/json');
echo json_encode(['text' => $text]);

function generateFullStandingsText($league, $standings, $stats) {
    $text = "🏆 *{$league['name']} - League Standings*\n";
    $text .= "📅 Updated: " . date('M j, Y g:i A') . "\n\n";
    
    foreach ($standings as $index => $team) {
        $pos = $index + 1;
        $emoji = $pos === 1 ? '👑' : ($pos <= 4 ? '🥉' : '⚽');
        $text .= "{$emoji} {$pos}. *{$team['name']}* - {$team['points']} pts\n";
        $text .= "   GP: {$team['played']} | W: {$team['wins']} | L: {$team['losses']} | GD: " . 
                 ($team['goal_difference'] >= 0 ? '+' : '') . $team['goal_difference'] . "\n\n";
    }
    
    $text .= "📊 *League Stats:*\n";
    $text .= "• Total Goals: {$stats['total_goals']}\n";
    $text .= "• Avg Goals/Game: {$stats['avg_goals_per_game']}\n";
    
    if ($stats['highest_scoring_team']) {
        $text .= "• Top Scorer: {$stats['highest_scoring_team']}\n";
    }
    
    if ($stats['best_defense']) {
        $text .= "• Best Defense: {$stats['best_defense']}\n";
    }
    
    $text .= "\n⚡ Generated by NCL League Platform";
    
    return $text;
}

function generateTop5StandingsText($league, $standings) {
    $text = "🏆 *{$league['name']} - Top 5 Standings*\n";
    $text .= "📅 " . date('M j, Y') . "\n\n";
    
    foreach (array_slice($standings, 0, 5) as $index => $team) {
        $pos = $index + 1;
        $emoji = $pos === 1 ? '👑' : ($pos <= 4 ? '🥉' : '⚽');
        $text .= "{$emoji} {$pos}. *{$team['name']}* - {$team['points']} pts ({$team['played']} GP)\n";
    }
    
    $text .= "\n⚡ Full standings available on NCL Platform";
    
    return $text;
}

function generateResultsText($league, $results) {
    $text = "🕐 *{$league['name']} - Recent Results*\n\n";
    
    foreach ($results as $result) {
        $date = date('M j', strtotime($result['match_date']));
        $text .= "⚽ *{$result['home_team']}* {$result['score_home']} - {$result['score_away']} *{$result['away_team']}*\n";
        $text .= "📅 {$date}\n\n";
    }
    
    $text .= "⚡ Generated by NCL League Platform";
    
    return $text;
}

function generateFixturesText($league, $fixtures) {
    $text = "📅 *{$league['name']} - Upcoming Fixtures*\n\n";
    
    foreach ($fixtures as $fixture) {
        $date = date('M j', strtotime($fixture['match_date']));
        $text .= "⚽ *{$fixture['home_team']}* vs *{$fixture['away_team']}*\n";
        $text .= "📅 {$date}";
        
        if (!empty($fixture['match_time'])) {
            $text .= " at " . date('g:i A', strtotime($fixture['match_time']));
        }
        
        if (!empty($fixture['venue'])) {
            $text .= "\n📍 {$fixture['venue']}";
        }
        
        $text .= "\n\n";
    }
    
    $text .= "⚡ Generated by NCL League Platform";
    
    return $text;
}

function generateWeeklyReportText($league, $standings, $stats, $conn, $leagueId) {
    $text = "📊 *{$league['name']} - Weekly Report*\n";
    $text .= "📅 " . date('M j, Y') . "\n\n";
    
    // Top 3 teams
    $text .= "🏆 *Top 3 Standings:*\n";
    foreach (array_slice($standings, 0, 3) as $index => $team) {
        $pos = $index + 1;
        $emoji = $pos === 1 ? '👑' : ($pos === 2 ? '🥈' : '🥉');
        $text .= "{$emoji} {$pos}. *{$team['name']}* - {$team['points']} pts\n";
    }
    
    $text .= "\n📈 *This Week's Stats:*\n";
    $text .= "• Matches Played: {$stats['matches_this_week']}\n";
    $text .= "• Goals Scored: {$stats['total_goals']}\n";
    $text .= "• Average Goals/Game: {$stats['avg_goals_per_game']}\n";
    
    // Recent results
    $results = getRecentResults($conn, $leagueId, 3);
    if (!empty($results)) {
        $text .= "\n🕐 *Latest Results:*\n";
        foreach ($results as $result) {
            $text .= "⚽ {$result['home_team']} {$result['score_home']}-{$result['score_away']} {$result['away_team']}\n";
        }
    }
    
    // Upcoming fixtures
    $fixtures = getUpcomingFixtures($conn, $leagueId, 3);
    if (!empty($fixtures)) {
        $text .= "\n📅 *Next Fixtures:*\n";
        foreach ($fixtures as $fixture) {
            $date = date('M j', strtotime($fixture['match_date']));
            $text .= "⚽ {$fixture['home_team']} vs {$fixture['away_team']} ({$date})\n";
        }
    }
    
    $text .= "\n⚡ Full details on NCL League Platform";
    
    return $text;
}
?>
